name: CMake

on:
  workflow_dispatch:
  
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone
      run: git clone https://github.com/Microsoft/vcpkg.git
      
    - name: Run bootstrap
      working-directory: vcpkg
      run: ./bootstrap-vcpkg.bat
      
    - name: Next command
      working-directory: vcpkg
      run: ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows
      
    - name: Remove Item
      run: Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
    
    - name: Make dir build
      run: mkdir build
      
    - name: Ab
      working-directory: build
      run: cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=.. -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
      
    - name: Ac
      working-directory: build
      run: cmake --build . --target install --config Release
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        path: bin
    
